### ISSUE TITLE
Cannot build for manual install

### ISSUE THREAD

**Issue by tylerwolf35** [r0man/asahi-guix#36]
Hello, thank you for your hard work on getting Guix to run on Apple Silicon via Asahi Linux.

I am running into error when I try to build using the example guix.scm file.

When I run the command to build  `guix system build --load-path=src asahi-guix.scm` I get the following:
```
ice-9/eval.scm:223:20: In procedure proc:
error: asahi-linux: unbound variable
hint: Did you forget `(use-modules (asahi guix packages linux))'?
```

I then tried to follow the hint and add the above module as well, but the error persists.

I have also set `GUIX_PACKAGE_PATH` to `~/asahi-guix/src/asahi/guix/packages/` but this does not help.

Based on the error I do not believe that this is the case, however I know that the latest sudo update can complicate new Guix builds on Silicon.

Any help would be appreciated.

Thanks!

**Comment by r0man** [comment]
Hi Tyler,

this repository is still in an experimental state. I would not recommend
using it at the moment unless you are an experienced Guix Hacker and want
to contribute to it.

There are still a lot of issues to be solved. Rust substitutes for example
aren't useable at the moment due to jemalloc not being built with large
page sizes. This means you have to compile it from source and tweak things
to get even a browser working. Long compilation times ahead.

For your specific issue. Things you could try:
- Make sure you added this repository as a channel
- use the pre-install script and maybe adjust it to add the src directory
to the guile load path (this might be missing)

There is a next branch in which I tried to update to the latest Guix, but
it needs more work to even boot. Somehow it hangs somewhere after Shepherd
starting up.

I'm traveling through Europe for the next months and only carry my work
laptop with me. I left the M1 at home, so I can't debug and test this at
the moment unfortunately.

Roman.

**Comment by tylerwolf35** [comment]
I have since been able to fix this, embarrassingly the issue appears to have arisen from the Guix installation on my Asahi system being out of date.

**Comment by r0man** [comment]
Nice, I'm glad you got it working.
